language: bash
dist: xenial
sudo: true
#python:
#- "2.7"
install:
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-pip python-setuptools libffi-dev python-nose
- pip2 install pyflakes --user
- pip2 install angr==7.8.9.26 --user
- pip2 install https://github.com/trailofbits/manticore/archive/last_python2.zip --user
- mkdir build
- cd build
- cmake ..
- sudo make install
- cd ..
env:
- TASK=ARITHMETIC
- TASK=CRASH
- TASK=FIXTURE
- TASK=KLEE
- TASK=LISTS
- TASK=ONEOF
- TASK=OVERFLOW
- TASK=PRIMES
- TASK=STREAMINGANDFORMATTING
- TASK=TAKEOVER
script:
- pyflakes bin/deepstate/*.py
- pyflakes tests/*.py
- if [ $TASK = ARITHMETIC ]; then nosetests tests/test_arithmetic.py ; fi
- if [ $TASK = CRASH ]; then nosetests tests/test_crash.py ; fi
- if [ $TASK = FIXTURE ]; then nosetests tests/test_fixture.py ; fi
- if [ $TASK = KLEE ]; then nosetests tests/test_klee.py ; fi
- if [ $TASK = LISTS ]; then nosetests tests/test_lists.py ; fi
- if [ $TASK = ONEOF ]; then nosetests tests/test_oneof.py ; fi
- if [ $TASK = OVERFLOW ]; then nosetests tests/test_overflow.py ; fi
- if [ $TASK = PRIMES ]; then nosetests tests/test_primes.py ; fi
- if [ $TASK = STREAMINGANDFORMATTING ]; then nosetests tests/test_streamingandformatting.py ; fi
- if [ $TASK = TAKEOVER ]; then nosetests tests/test_takeover.py ; fi

